"""Bayesian network for the Meridian Drive Systems supply-chain demo.

A ~$2.5B EV-traction-motor maker exposed to rare-earth-magnet and power-semi
supply shocks. The model is a four-layer DAG, not a flat naive-Bayes star — that
depth is the point: it exercises the things a Bayesian network is *for*.

    DRIVERS      Geo_Exposure   Supplier_Health   Route_Status
                      │  ╲            │   ╲            │
    MECHANISMS     Magnet_Supply ◄────┴────► Power_Semi_Supply   (the two BOM
                          ╲                 ╱                      bottlenecks)
    LATENT              Disruption_Regime  (Normal → Severe)
                     ╱     │       ╲            ╲
    EMISSIONS  LeadTime  ForceMaj  Expedite   Input_Price_Spike ◄── Geo_Exposure
    (signals)                                  (explaining-away: macro RE pricing)
    IMPACTS    Production_Output → On_Time_Delivery     Gross_Margin_Hit
    (the $$$)                                            ↑ Production_Output

What the depth buys (none of it visible in a star):
  * Mechanism: drivers reach the regime *through* two named component
    bottlenecks (rare-earth magnets, power semiconductors). Supplier_Health is a
    shared parent of both, coupling them.
  * Explaining-away: Input_Price_Spike has the regime AND Geo_Exposure as
    parents, so a price spike under high geopolitical exposure is partly
    explained by macro rare-earth pricing and implicates the regime less.
  * Propagation to a decision: the regime drives lost production → missed OEM
    deliveries → gross-margin hit, so a headline updates a P&L-relevant node.

All CPTs are *illustrative elicited anchors* (Plan: to be calibrated via the
elicitation pipeline). The multi-parent CPTs (mechanisms, latent, price spike,
margin hit) are generated by the ranked-node method (src.cpt_builders) from a few
weights + anchor distributions, not hand-filled cell by cell.
"""
from __future__ import annotations

from itertools import product
from typing import Dict, List, Sequence, Tuple

from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import DiscreteBayesianNetwork

from src.cpt_builders import ranked_node_cpt

STATES: Dict[str, List[str]] = {
    # drivers (exogenous)
    "Geo_Exposure": ["Low", "Elevated", "High"],
    "Supplier_Health": ["Healthy", "Watch", "Distressed"],
    "Route_Status": ["Open", "Congested", "Disrupted"],
    # mechanism layer (the two critical-input bottlenecks)
    "Magnet_Supply": ["Ample", "Tight", "Critical"],
    "Power_Semi_Supply": ["Ample", "Tight", "Critical"],
    # latent regime
    "Disruption_Regime": ["Normal", "Single_Supplier_Stress", "Multi_Node_Ripple", "Severe"],
    # driver indicator
    "Policy_Headlines": ["Quiet", "Active", "Escalating"],
    # emissions (observable signals the translator reads)
    "Lead_Time_Slippage": ["OnTime", "Slipping", "Blown"],
    "Force_Majeure_Notices": ["None", "Isolated", "Multiple"],
    "Input_Price_Spike": ["Stable", "Rising", "Spiking"],
    "Expedite_Spend": ["Baseline", "Up", "Surging"],
    # impacts (consequences — the P&L story; inferred, not observed)
    "Production_Output": ["OnPlan", "Reduced", "Halted"],
    "On_Time_Delivery": ["Met", "AtRisk", "Missed"],
    "Gross_Margin_Hit": ["Minimal", "Moderate", "Heavy"],
}

_S = "Disruption_Regime"
_DRIVERS = ["Geo_Exposure", "Supplier_Health", "Route_Status"]
_MECHANISMS = ["Magnet_Supply", "Power_Semi_Supply"]
# Regime-only emissions; Input_Price_Spike is handled separately (it also has a
# direct Geo_Exposure parent — the explaining-away edge).
_REGIME_EMISSIONS = ["Lead_Time_Slippage", "Force_Majeure_Notices", "Expedite_Spend"]
# The nodes the translator can set evidence on (the "read surface").
_EMISSIONS = _REGIME_EMISSIONS + ["Input_Price_Spike"]
_IMPACTS = ["Production_Output", "On_Time_Delivery", "Gross_Margin_Hit"]

EDGES_LATENT: List[Tuple[str, str]] = (
    # drivers → mechanisms
    [("Geo_Exposure", "Magnet_Supply"), ("Supplier_Health", "Magnet_Supply"),
     ("Route_Status", "Power_Semi_Supply"), ("Supplier_Health", "Power_Semi_Supply")]
    # mechanisms → regime
    + [(m, _S) for m in _MECHANISMS]
    # regime → emissions
    + [(_S, e) for e in _REGIME_EMISSIONS]
    + [(_S, "Input_Price_Spike"), ("Geo_Exposure", "Input_Price_Spike")]  # explaining-away
    # regime → impacts → downstream impacts
    + [(_S, "Production_Output"), ("Production_Output", "On_Time_Delivery"),
       (_S, "Gross_Margin_Hit"), ("Production_Output", "Gross_Margin_Hit")]
    # driver indicator
    + [("Geo_Exposure", "Policy_Headlines")]
)
# Meridian ships a single (latent-regime) topology; expose the same edges as the
# "labelling" alias so engine code that references either name works.
EDGES = EDGES_LATENT


def _cpd(var: str, parents: Sequence[str], table: Dict[Tuple[str, ...], Sequence[float]]) -> TabularCPD:
    """{parent-state-tuple: child-prob-vector} → TabularCPD (canonical column order)."""
    var_states = STATES[var]
    parent_states = [STATES[p] for p in parents]
    parent_cards = [len(s) for s in parent_states]
    columns = list(product(*parent_states)) if parents else [()]
    values: List[List[float]] = [[0.0] * len(columns) for _ in var_states]
    for col_idx, key in enumerate(columns):
        probs = table[key] if parents else table[()]
        if abs(sum(probs) - 1.0) > 1e-8:
            raise ValueError(f"CPT column for {var}{key} sums to {sum(probs)}")
        for row_idx, p in enumerate(probs):
            values[row_idx][col_idx] = p
    state_names = {var: var_states}
    for p, s in zip(parents, parent_states):
        state_names[p] = s
    return TabularCPD(
        variable=var, variable_card=len(var_states), values=values,
        evidence=list(parents) if parents else None,
        evidence_card=parent_cards if parents else None, state_names=state_names,
    )


# --- driver priors (elicited base rates; example mid-risk manufacturer) -----
_PRIORS = {
    "Geo_Exposure": [0.45, 0.40, 0.15],
    "Supplier_Health": [0.60, 0.28, 0.12],
    "Route_Status": [0.62, 0.30, 0.08],
}

# --- mechanism CPTs via ranked-node -----------------------------------------
# Magnet_Supply  ← Geo_Exposure (export controls dominate), Supplier_Health.
# Power_Semi_Supply ← Route_Status (inbound logistics dominate), Supplier_Health.
# Shared 3-state severity anchors over [Ample, Tight, Critical].
_MECH_ANCHORS = [
    (0.00, [0.90, 0.08, 0.02]),
    (0.50, [0.45, 0.40, 0.15]),
    (1.00, [0.08, 0.41, 0.51]),
]
_MAGNET_WEIGHTS = {"Geo_Exposure": 0.60, "Supplier_Health": 0.40}
_POWER_SEMI_WEIGHTS = {"Route_Status": 0.55, "Supplier_Health": 0.45}

# --- latent CPT via ranked-node (2 mechanisms → 9 columns) ------------------
_LATENT_WEIGHTS = {"Magnet_Supply": 0.55, "Power_Semi_Supply": 0.45}
_LATENT_ANCHORS = [
    (0.00, [0.90, 0.08, 0.015, 0.005]),
    (0.33, [0.55, 0.30, 0.12, 0.03]),
    (0.67, [0.20, 0.35, 0.32, 0.13]),
    (1.00, [0.03, 0.17, 0.40, 0.40]),
]

# --- regime-only emission CPTs P(emission | regime); rows = regime order -----
# (Normal, Single_Supplier_Stress, Multi_Node_Ripple, Severe)
_EMISSION_TABLES = {
    "Lead_Time_Slippage": [[0.85, 0.13, 0.02], [0.45, 0.45, 0.10], [0.18, 0.52, 0.30], [0.05, 0.35, 0.60]],
    "Force_Majeure_Notices": [[0.93, 0.06, 0.01], [0.55, 0.40, 0.05], [0.22, 0.50, 0.28], [0.05, 0.35, 0.60]],
    "Expedite_Spend": [[0.88, 0.10, 0.02], [0.50, 0.40, 0.10], [0.22, 0.48, 0.30], [0.06, 0.34, 0.60]],
}

# --- explaining-away emission: Input_Price_Spike ← regime + Geo_Exposure -----
# A price spike is driven by the regime AND directly by geopolitics (macro
# rare-earth pricing), so under high Geo_Exposure a spike implicates the regime
# less. 3-state anchors over [Stable, Rising, Spiking].
_PRICE_WEIGHTS = {"Disruption_Regime": 0.60, "Geo_Exposure": 0.40}
_PRICE_ANCHORS = [
    (0.00, [0.85, 0.13, 0.02]),
    (0.50, [0.45, 0.42, 0.13]),
    (1.00, [0.10, 0.40, 0.50]),
]

# --- impact layer (consequences) --------------------------------------------
# Production_Output ← regime; rows = regime order.
_PRODUCTION_TABLE = [[0.95, 0.045, 0.005], [0.78, 0.20, 0.02], [0.45, 0.45, 0.10], [0.12, 0.48, 0.40]]
# On_Time_Delivery ← Production_Output; rows = (OnPlan, Reduced, Halted).
_OTD_TABLE = {
    ("OnPlan",): [0.93, 0.06, 0.01],
    ("Reduced",): [0.45, 0.42, 0.13],
    ("Halted",): [0.08, 0.32, 0.60],
}
# Gross_Margin_Hit ← regime + Production_Output (ranked-node); [Minimal, Moderate, Heavy].
_MARGIN_WEIGHTS = {"Disruption_Regime": 0.50, "Production_Output": 0.50}
_MARGIN_ANCHORS = [
    (0.00, [0.90, 0.09, 0.01]),
    (0.50, [0.40, 0.45, 0.15]),
    (1.00, [0.08, 0.42, 0.50]),
]

# --- driver-indicator CPT P(Policy_Headlines | Geo_Exposure) ----------------
_POLICY_TABLE = {
    ("Low",): [0.80, 0.18, 0.02],
    ("Elevated",): [0.45, 0.45, 0.10],
    ("High",): [0.15, 0.45, 0.40],
}

SCENARIO_NARRATIVES: Dict[str, str] = {
    "Normal": "Supply network operating within tolerance; no action beyond monitoring.",
    "Single_Supplier_Stress": "One critical supplier or lane under strain; localised lead-time and price pressure.",
    "Multi_Node_Ripple": "Disruption propagating across multiple suppliers/lanes; broad lead-time slippage and price spikes.",
    "Severe": "Severe multi-node disruption; production-stopping shortages, force-majeure clustering, surging expedite spend.",
}

# Modal emission signature per regime (illustrative; used where a pack exposes one).
SCENARIO_SIGNATURES: Dict[str, Tuple[str, str, str, str]] = {
    "Normal": ("OnTime", "None", "Stable", "Baseline"),
    "Single_Supplier_Stress": ("Slipping", "Isolated", "Stable", "Up"),
    "Multi_Node_Ripple": ("Slipping", "Isolated", "Rising", "Up"),
    "Severe": ("Blown", "Multiple", "Spiking", "Surging"),
}


def build_network(topology: str = "latent_regime") -> DiscreteBayesianNetwork:
    """Assemble the Meridian latent-regime network. ``topology`` accepts
    ``"latent_regime"`` (default) or its ``"labelling"`` alias — Meridian ships a
    single topology."""
    if topology not in ("latent_regime", "labelling"):
        raise ValueError(f"Unknown topology {topology!r}; Meridian has one topology.")
    net = DiscreteBayesianNetwork(EDGES_LATENT)
    cpds = [_cpd(d, (), {(): _PRIORS[d]}) for d in _DRIVERS]

    # mechanism layer
    cpds.append(_cpd("Magnet_Supply", ("Geo_Exposure", "Supplier_Health"), ranked_node_cpt(
        ["Geo_Exposure", "Supplier_Health"], STATES, _MAGNET_WEIGHTS,
        STATES["Magnet_Supply"], _MECH_ANCHORS,
    )))
    cpds.append(_cpd("Power_Semi_Supply", ("Route_Status", "Supplier_Health"), ranked_node_cpt(
        ["Route_Status", "Supplier_Health"], STATES, _POWER_SEMI_WEIGHTS,
        STATES["Power_Semi_Supply"], _MECH_ANCHORS,
    )))

    # latent regime ← mechanisms
    cpds.append(_cpd(_S, _MECHANISMS, ranked_node_cpt(
        _MECHANISMS, STATES, _LATENT_WEIGHTS, STATES[_S], _LATENT_ANCHORS,
    )))

    # regime-only emissions
    for emission in _REGIME_EMISSIONS:
        table = {(r,): row for r, row in zip(STATES[_S], _EMISSION_TABLES[emission])}
        cpds.append(_cpd(emission, (_S,), table))

    # explaining-away emission
    cpds.append(_cpd("Input_Price_Spike", (_S, "Geo_Exposure"), ranked_node_cpt(
        [_S, "Geo_Exposure"], STATES, _PRICE_WEIGHTS,
        STATES["Input_Price_Spike"], _PRICE_ANCHORS,
    )))

    # impact layer
    prod_table = {(r,): row for r, row in zip(STATES[_S], _PRODUCTION_TABLE)}
    cpds.append(_cpd("Production_Output", (_S,), prod_table))
    cpds.append(_cpd("On_Time_Delivery", ("Production_Output",), _OTD_TABLE))
    cpds.append(_cpd("Gross_Margin_Hit", (_S, "Production_Output"), ranked_node_cpt(
        [_S, "Production_Output"], STATES, _MARGIN_WEIGHTS,
        STATES["Gross_Margin_Hit"], _MARGIN_ANCHORS,
    )))

    # driver indicator
    cpds.append(_cpd("Policy_Headlines", ("Geo_Exposure",), _POLICY_TABLE))

    net.add_cpds(*cpds)
    net.check_model()
    return net


__all__ = [
    "STATES", "EDGES", "EDGES_LATENT", "SCENARIO_NARRATIVES",
    "SCENARIO_SIGNATURES", "build_network",
]
