"""Bayesian network for the Meridian Drive Systems supply-chain demo.

A ~$2.5B EV-traction-motor maker exposed to rare-earth-magnet and power-semi
supply shocks. Latent ``Disruption_Regime`` (Normal → Severe) is inferred from
observable emissions (lead-time slippage, force-majeure notices, input-price
spikes, expedite spend) given three drivers (geopolitical exposure, supplier
financial health, logistics-route status). A driver indicator
(``Policy_Headlines``) hangs off ``Geo_Exposure`` to show the translator updating
the cause side.

All CPTs are *illustrative elicited anchors* (Plan: to be calibrated via the
elicitation pipeline). The latent CPT is generated by the ranked-node method
(src.cpt_builders) from 3 weights + 4 anchor distributions, not 108 hand cells.
"""
from __future__ import annotations

from itertools import product
from typing import Dict, List, Sequence, Tuple

from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import DiscreteBayesianNetwork

from src.cpt_builders import ranked_node_cpt

STATES: Dict[str, List[str]] = {
    "Geo_Exposure": ["Low", "Elevated", "High"],
    "Supplier_Health": ["Healthy", "Watch", "Distressed"],
    "Route_Status": ["Open", "Congested", "Disrupted"],
    "Disruption_Regime": ["Normal", "Single_Supplier_Stress", "Multi_Node_Ripple", "Severe"],
    "Policy_Headlines": ["Quiet", "Active", "Escalating"],
    "Lead_Time_Slippage": ["OnTime", "Slipping", "Blown"],
    "Force_Majeure_Notices": ["None", "Isolated", "Multiple"],
    "Input_Price_Spike": ["Stable", "Rising", "Spiking"],
    "Expedite_Spend": ["Baseline", "Up", "Surging"],
}

_S = "Disruption_Regime"
_DRIVERS = ["Geo_Exposure", "Supplier_Health", "Route_Status"]
_EMISSIONS = ["Lead_Time_Slippage", "Force_Majeure_Notices", "Input_Price_Spike", "Expedite_Spend"]

EDGES_LATENT: List[Tuple[str, str]] = (
    [(d, _S) for d in _DRIVERS]
    + [(_S, e) for e in _EMISSIONS]
    + [("Geo_Exposure", "Policy_Headlines")]
)
# Meridian ships a single (latent-regime) topology; expose the same edges as the
# "labelling" alias so engine code that references either name works.
EDGES = EDGES_LATENT


def _cpd(var: str, parents: Sequence[str], table: Dict[Tuple[str, ...], Sequence[float]]) -> TabularCPD:
    """{parent-state-tuple: child-prob-vector} → TabularCPD (canonical column order)."""
    var_states = STATES[var]
    parent_states = [STATES[p] for p in parents]
    parent_cards = [len(s) for s in parent_states]
    columns = list(product(*parent_states)) if parents else [()]
    values: List[List[float]] = [[0.0] * len(columns) for _ in var_states]
    for col_idx, key in enumerate(columns):
        probs = table[key] if parents else table[()]
        if abs(sum(probs) - 1.0) > 1e-8:
            raise ValueError(f"CPT column for {var}{key} sums to {sum(probs)}")
        for row_idx, p in enumerate(probs):
            values[row_idx][col_idx] = p
    state_names = {var: var_states}
    for p, s in zip(parents, parent_states):
        state_names[p] = s
    return TabularCPD(
        variable=var, variable_card=len(var_states), values=values,
        evidence=list(parents) if parents else None,
        evidence_card=parent_cards if parents else None, state_names=state_names,
    )


# --- driver priors (elicited base rates; example mid-risk manufacturer) -----
_PRIORS = {
    "Geo_Exposure": [0.45, 0.40, 0.15],
    "Supplier_Health": [0.60, 0.28, 0.12],
    "Route_Status": [0.62, 0.30, 0.08],
}

# --- latent CPT via ranked-node (3 weights + 4 anchors → 27 columns) --------
_LATENT_WEIGHTS = {"Geo_Exposure": 0.30, "Supplier_Health": 0.42, "Route_Status": 0.28}
_LATENT_ANCHORS = [
    (0.00, [0.90, 0.08, 0.015, 0.005]),
    (0.33, [0.55, 0.30, 0.12, 0.03]),
    (0.67, [0.20, 0.35, 0.32, 0.13]),
    (1.00, [0.03, 0.17, 0.40, 0.40]),
]

# --- emission CPTs P(emission | Disruption_Regime); rows = regime order -----
# (Normal, Single_Supplier_Stress, Multi_Node_Ripple, Severe)
_EMISSION_TABLES = {
    "Lead_Time_Slippage": [[0.85, 0.13, 0.02], [0.45, 0.45, 0.10], [0.18, 0.52, 0.30], [0.05, 0.35, 0.60]],
    "Force_Majeure_Notices": [[0.93, 0.06, 0.01], [0.55, 0.40, 0.05], [0.22, 0.50, 0.28], [0.05, 0.35, 0.60]],
    "Input_Price_Spike": [[0.82, 0.16, 0.02], [0.62, 0.31, 0.07], [0.33, 0.50, 0.17], [0.12, 0.45, 0.43]],
    "Expedite_Spend": [[0.88, 0.10, 0.02], [0.50, 0.40, 0.10], [0.22, 0.48, 0.30], [0.06, 0.34, 0.60]],
}

# --- driver-indicator CPT P(Policy_Headlines | Geo_Exposure) ----------------
_POLICY_TABLE = {
    ("Low",): [0.80, 0.18, 0.02],
    ("Elevated",): [0.45, 0.45, 0.10],
    ("High",): [0.15, 0.45, 0.40],
}

SCENARIO_NARRATIVES: Dict[str, str] = {
    "Normal": "Supply network operating within tolerance; no action beyond monitoring.",
    "Single_Supplier_Stress": "One critical supplier or lane under strain; localised lead-time and price pressure.",
    "Multi_Node_Ripple": "Disruption propagating across multiple suppliers/lanes; broad lead-time slippage and price spikes.",
    "Severe": "Severe multi-node disruption; production-stopping shortages, force-majeure clustering, surging expedite spend.",
}

# Modal emission signature per regime (illustrative; used where a pack exposes one).
SCENARIO_SIGNATURES: Dict[str, Tuple[str, str, str, str]] = {
    "Normal": ("OnTime", "None", "Stable", "Baseline"),
    "Single_Supplier_Stress": ("Slipping", "Isolated", "Stable", "Up"),
    "Multi_Node_Ripple": ("Slipping", "Isolated", "Rising", "Up"),
    "Severe": ("Blown", "Multiple", "Spiking", "Surging"),
}


def build_network(topology: str = "latent_regime") -> DiscreteBayesianNetwork:
    """Assemble the Meridian latent-regime network. ``topology`` accepts
    ``"latent_regime"`` (default) or its ``"labelling"`` alias — Meridian ships a
    single topology."""
    if topology not in ("latent_regime", "labelling"):
        raise ValueError(f"Unknown topology {topology!r}; Meridian has one topology.")
    net = DiscreteBayesianNetwork(EDGES_LATENT)
    cpds = [_cpd(d, (), {(): _PRIORS[d]}) for d in _DRIVERS]
    cpds.append(_cpd(_S, _DRIVERS, ranked_node_cpt(
        _DRIVERS, STATES, _LATENT_WEIGHTS, STATES[_S], _LATENT_ANCHORS,
    )))
    for emission in _EMISSIONS:
        table = {(r,): row for r, row in zip(STATES[_S], _EMISSION_TABLES[emission])}
        cpds.append(_cpd(emission, (_S,), table))
    cpds.append(_cpd("Policy_Headlines", ("Geo_Exposure",), _POLICY_TABLE))
    net.add_cpds(*cpds)
    net.check_model()
    return net


__all__ = [
    "STATES", "EDGES", "EDGES_LATENT", "SCENARIO_NARRATIVES",
    "SCENARIO_SIGNATURES", "build_network",
]
