"""Derive the latent-regime anchor CPTs from the current labelling network and write
them as literal values to ``src/cpt_data.py``.

This is the one-off, offline bootstrap of Plan 1 §B.1 item 2. Because ``Scenario`` is a
*leaf* in the labelling network, the current joint already equals the augmented joint
P~(S, D,T,P,M,C,U...) = P(S|D,T,P)·P_cur(rest). The four latent-regime CPTs are therefore
exact conditionals of the current joint, obtained by marginalise-and-divide via pgmpy
variable elimination:

    P(S | M,C)         = P~(S,M,C)        / P~(M,C)
    P(D | S,M,C)       = P~(D,S,M,C)      / P~(S,M,C)
    P(T | S,U1,U3,M)   = P~(T,S,U1,U3,M)  / P~(S,U1,U3,M)
    P(P | S,U1,U3,U2)  = P~(P,S,U1,U3,U2) / P~(S,U1,U3,U2)

Guards: a small floor EPS_MIN (renormalised) keeps every cell strictly positive so Bayes
factors stay finite; a 0/0 fallback to the S-free emission protects any near-zero parent
cell (never triggered for the current network, where P(M,C) etc. are strictly positive).

Honest scope (Plan §B.1 / §D): the inversion transfers emission MODES faithfully and
supplies degeneracy-safe non-zero TAILS, but the tail magnitudes are classifier-boundary
artefacts, not elicited regime belief, until Plan 4 Layer 2 re-elicits them.

Run:  pixi run python scripts/derive_latent_regime_anchors.py
Then: src/cpt_data.py is regenerated (commit it). A reproducibility test asserts the
committed values match a fresh derivation.
"""
from __future__ import annotations

import datetime as _dt
import sys
from itertools import product
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import VariableElimination

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from packs.hormuz.network import STATES, build_network  # noqa: E402

# Node short-names
S = "Scenario"
D = "Energy_Infrastructure_Damage"
T = "Conflict_Duration"
P = "Diplomatic_Resolution_Path"
M = "US_Military_Response"
C = "Strait_Operationally_Closed"
U1 = "US_Iran_Negotiations"
U2 = "Iranian_Regime_Stability"
U3 = "Third_Party_Mediation"

# child -> canonical parent order (each emission keeps its original parents and gains S)
LATENT_CPT_PARENTS: Dict[str, List[str]] = {
    S: [M, C],
    D: [S, M, C],
    T: [S, U1, U3, M],
    P: [S, U1, U3, U2],
}

EPS_MIN = 1e-4
DENOM_TINY = 1e-12


def _conditional_factor(engine, child: str, parents: Sequence[str]) -> DiscreteFactor:
    num = engine.query([child] + list(parents), evidence={}, show_progress=False)
    den = engine.query(list(parents), evidence={}, show_progress=False)
    cond = num.divide(den, inplace=False)
    if child != S and S in parents:
        s_free = [p for p in parents if p != S]
        fb = None
        if s_free:
            fb = engine.query([child] + s_free, evidence={}, show_progress=False).divide(
                engine.query(s_free, evidence={}, show_progress=False), inplace=False)
        for key in product(*[STATES[p] for p in parents]):
            assign = dict(zip(parents, key))
            if den.get_value(**assign) < DENOM_TINY:
                for cs in STATES[child]:
                    val = (fb.get_value(**{p: assign[p] for p in s_free}, **{child: cs})
                           if fb is not None else 1.0 / len(STATES[child]))
                    cond.set_value(val, **{child: cs}, **assign)
    return cond


def _derive_cpt(engine, child: str, parents: Sequence[str]) -> Dict[Tuple[str, ...], List[float]]:
    cond = _conditional_factor(engine, child, parents)
    out: Dict[Tuple[str, ...], List[float]] = {}
    for key in product(*[STATES[p] for p in parents]):
        assign = dict(zip(parents, key))
        vec = np.array([cond.get_value(**{child: cs}, **assign) for cs in STATES[child]])
        vec = np.clip(np.nan_to_num(vec, nan=1.0 / len(STATES[child])), EPS_MIN, None)
        out[key] = (vec / vec.sum()).tolist()
    return out


def derive_latent_cpts() -> Dict[str, Dict[Tuple[str, ...], List[float]]]:
    """Derive all four latent-regime CPTs from the current labelling network."""
    engine = VariableElimination(build_network("labelling"))
    return {child: _derive_cpt(engine, child, parents)
            for child, parents in LATENT_CPT_PARENTS.items()}


def _fmt_cpts(cpts: Dict[str, Dict[Tuple[str, ...], List[float]]]) -> str:
    lines = ["LATENT_CPTS: Dict[str, Dict[Tuple[str, ...], List[float]]] = {"]
    for child, table in cpts.items():
        lines.append(f"    {child!r}: {{")
        for key, vec in table.items():
            lines.append(f"        {key!r}: {list(vec)!r},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


HEADER = '''"""AUTO-GENERATED by scripts/derive_latent_regime_anchors.py — do not edit by hand.

Latent-regime anchor CPTs derived from the current labelling network (Plan 1 §B.1).
Regenerate with:  pixi run python scripts/derive_latent_regime_anchors.py
Generated: {ts}

These are a v1 bootstrap: emission MODES are faithful, but off-mode TAIL magnitudes are
classifier-boundary artefacts (not elicited belief) until Plan 4 Layer 2 re-elicits them.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

'''


def render_module(cpts) -> str:
    parts = [HEADER.format(ts=_dt.date.today().isoformat())]
    parts.append("LATENT_CPT_PARENTS: Dict[str, List[str]] = " + repr(LATENT_CPT_PARENTS))
    parts.append("\n" + _fmt_cpts(cpts))
    parts.append('\n__all__ = ["LATENT_CPTS", "LATENT_CPT_PARENTS"]\n')
    return "\n".join(parts)


def main() -> None:
    cpts = derive_latent_cpts()
    target = Path(__file__).resolve().parents[1] / "packs" / "hormuz" / "cpt_data.py"
    target.write_text(render_module(cpts))
    n = sum(len(t) for t in cpts.values())
    print(f"Wrote {target} ({n} CPT columns across {len(cpts)} CPTs).")


if __name__ == "__main__":
    main()
