"""layer 0 elicitation schema

Revision ID: 621ed128b0d3
Revises: 
Create Date: 2026-06-09 01:15:34.577206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621ed128b0d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('topology', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_networks')),
    sa.UniqueConstraint('name', name=op.f('uq_networks_name'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('provider_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=16), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('deployment', 'provider', 'source', 'owner_user_id', name='scope')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_deployment'), ['deployment'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('seed_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_sets')),
    sa.UniqueConstraint('name', name=op.f('uq_seed_sets_name'))
    )
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name=op.f('fk_calibration_runs_network_id_networks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration_runs'))
    )
    op.create_table('cpts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=128), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['cpt_versions.id'], name='fk_cpts_current_version_id_cpt_versions', use_alter=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name=op.f('fk_cpts_network_id_networks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpts')),
    sa.UniqueConstraint('network_id', 'node', name='network_node')
    )
    op.create_table('elicitation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('aggregated_output', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name=op.f('fk_elicitation_sessions_network_id_networks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elicitation_sessions'))
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=128), nullable=False),
    sa.Column('realised_state', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name=op.f('fk_outcomes_network_id_networks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('cpt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('kappa', sa.Float(), nullable=True),
    sa.Column('kappa_level', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cpt_id'], ['cpts.id'], name=op.f('fk_cpt_versions_cpt_id_cpts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cpt_versions_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpt_versions'))
    )
    op.create_table('elicitation_session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['elicitation_sessions.id'], name=op.f('fk_elicitation_session_events_session_id_elicitation_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elicitation_session_events'))
    )
    op.create_table('experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('base_model', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('config_fingerprint', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experts')),
    sa.UniqueConstraint('kind', 'base_model', 'role', 'config_fingerprint', name='identity')
    )
    op.create_table('contamination_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('seed_set_id', sa.Integer(), nullable=False),
    sa.Column('seed_ref', sa.String(length=128), nullable=False),
    sa.Column('probe', sa.String(length=32), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], name=op.f('fk_contamination_checks_expert_id_experts')),
    sa.ForeignKeyConstraint(['seed_set_id'], ['seed_sets.id'], name=op.f('fk_contamination_checks_seed_set_id_seed_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contamination_checks'))
    )
    op.create_table('cpt_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpt_version_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('elicited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('kappa_level', sa.String(length=16), nullable=True),
    sa.Column('calibration_score', sa.Float(), nullable=True),
    sa.Column('model_set', sa.JSON(), nullable=True),
    sa.Column('correlation_note', sa.Text(), nullable=True),
    sa.Column('contamination_summary', sa.JSON(), nullable=True),
    sa.Column('is_ai_sourced', sa.Boolean(), nullable=False),
    sa.Column('human_signed_off_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cpt_version_id'], ['cpt_versions.id'], name=op.f('fk_cpt_provenance_cpt_version_id_cpt_versions')),
    sa.ForeignKeyConstraint(['human_signed_off_by'], ['users.id'], name=op.f('fk_cpt_provenance_human_signed_off_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['elicitation_sessions.id'], name=op.f('fk_cpt_provenance_session_id_elicitation_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cpt_provenance')),
    sa.UniqueConstraint('cpt_version_id', name=op.f('uq_cpt_provenance_cpt_version_id'))
    )
    op.create_table('expert_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('seed_set_id', sa.Integer(), nullable=False),
    sa.Column('calibration_score', sa.Float(), nullable=True),
    sa.Column('information_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('kappa_cap', sa.String(length=16), nullable=True),
    sa.Column('scoring_mode', sa.String(length=32), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], name=op.f('fk_expert_calibration_expert_id_experts')),
    sa.ForeignKeyConstraint(['seed_set_id'], ['seed_sets.id'], name=op.f('fk_expert_calibration_seed_set_id_seed_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_calibration'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_calibration')
    op.drop_table('cpt_provenance')
    op.drop_table('contamination_checks')
    op.drop_table('experts')
    op.drop_table('elicitation_session_events')
    op.drop_table('cpt_versions')
    op.drop_table('users')
    op.drop_table('outcomes')
    op.drop_table('elicitation_sessions')
    op.drop_table('cpts')
    op.drop_table('calibration_runs')
    op.drop_table('seed_sets')
    op.drop_table('roles')
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_deployment'))

    op.drop_table('provider_credentials')
    op.drop_table('permissions')
    op.drop_table('networks')
    # ### end Alembic commands ###
